import type { Term } from './types';

export const ACTION: Term[] = [
  {
    id: 'open-raise',
    en: 'Open raise',
    ja: 'オープンレイズ',
    kana: 'おーぷんれいず',
    aliases: ['open', 'RFI'],
    def: {
      ja: 'プリフロップで、まだ誰も参加していないポットに最初にレイズすること。',
      en: 'The first raise preflop into a pot that nobody has entered yet.',
    },
    example: { en: 'He open-raised to 2.5bb from the cutoff.', ja: 'カットオフから 2.5bb にオープンレイズした。' },
  },
  {
    id: 'limp',
    en: 'Limp',
    ja: 'リンプ',
    kana: 'りんぷ',
    aliases: ['open limp'],
    def: {
      ja: 'プリフロップでレイズせず、ビッグブラインドと同額をコールして参加すること。',
      en: 'Entering the pot preflop by just calling the big blind instead of raising.',
    },
    example: { en: 'Three players limped before the button raised.', ja: 'ボタンがレイズする前に3人がリンプした。' },
  },
  {
    id: 'call',
    en: 'Call',
    ja: 'コール',
    kana: 'こーる',
    def: {
      ja: '直前のベットやレイズと同じ額を出して、ハンドを続けること。',
      en: 'Matching the current bet or raise to stay in the hand.',
    },
    example: { en: 'I called the river bet with second pair.', ja: 'セカンドペアでリバーのベットにコールした。' },
  },
  {
    id: 'fold',
    en: 'Fold',
    ja: 'フォールド',
    kana: 'ふぉーるど',
    def: {
      ja: 'ハンドを捨てて、そのポットから降りること。',
      en: 'Giving up your hand and dropping out of the pot.',
    },
    example: { en: 'Folding was the right play against that shove.', ja: 'あのオールインにはフォールドが正解だった。' },
  },
  {
    id: 'check',
    en: 'Check',
    ja: 'チェック',
    kana: 'ちぇっく',
    def: {
      ja: 'ベットがないときに、チップを出さずに行動を次の人へ回すこと。',
      en: 'Passing the action without betting when nobody has bet yet.',
    },
    example: { en: 'Both players checked the turn.', ja: 'ターンは2人ともチェックした。' },
  },
  {
    id: 'bet',
    en: 'Bet',
    ja: 'ベット',
    kana: 'べっと',
    def: {
      ja: 'そのストリートで最初にチップを出すこと。',
      en: 'Putting the first chips into the pot on a street.',
    },
    example: { en: 'She bet half the pot on the flop.', ja: 'フロップでポットの半分をベットした。' },
  },
  {
    id: 'raise',
    en: 'Raise',
    ja: 'レイズ',
    kana: 'れいず',
    def: {
      ja: '相手のベットより多い額を出して、賭け金を引き上げること。',
      en: 'Increasing the size of the current bet.',
    },
    example: { en: 'He raised to three times the bet.', ja: 'ベットの3倍にレイズした。' },
  },
  {
    id: '3-bet',
    en: '3-bet',
    ja: 'スリーベット',
    kana: 'すりーべっと',
    aliases: ['3bet', 'three-bet', 'reraise', '3ベット'],
    def: {
      ja: 'オープンレイズに対して、さらにレイズすること。プリフロップでは3回目のベットにあたる。',
      en: 'A re-raise over an open raise; preflop it is the third bet, counting the blind.',
    },
    example: { en: 'He 3-bet from the button.', ja: 'ボタンから3ベットした。' },
  },
  {
    id: '4-bet',
    en: '4-bet',
    ja: 'フォーベット',
    kana: 'ふぉーべっと',
    aliases: ['4bet', 'four-bet', '4ベット'],
    def: {
      ja: 'スリーベットに対して、さらにレイズすること。',
      en: 'A re-raise over a 3-bet.',
    },
    example: { en: 'Facing a 4-bet, only premium hands continue.', ja: '4ベットを受けたら、続けるのはプレミアムハンドだけだ。' },
  },
  {
    id: '5-bet',
    en: '5-bet',
    ja: 'ファイブベット',
    kana: 'ふぁいぶべっと',
    aliases: ['5bet', 'five-bet', '5ベット'],
    def: {
      ja: 'フォーベットに対して、さらにレイズすること。100bb ではたいていオールインになる。',
      en: 'A re-raise over a 4-bet, usually all-in at 100bb deep.',
    },
    example: { en: 'He 5-bet shoved with aces.', ja: 'エースのペアで5ベットオールインした。' },
  },
  {
    id: 'cold-call',
    en: 'Cold call',
    ja: 'コールドコール',
    kana: 'こーるどこーる',
    aliases: ['flat'],
    def: {
      ja: 'まだチップを入れていない状態で、他人のレイズにコールすること。',
      en: 'Calling a raise when you have no chips in the pot yet.',
    },
    example: { en: 'Cold calling from the small blind is often a mistake.', ja: 'スモールブラインドからのコールドコールはミスになりやすい。' },
  },
  {
    id: 'squeeze',
    en: 'Squeeze',
    ja: 'スクイーズ',
    kana: 'すくいーず',
    def: {
      ja: 'オープンレイズとそのコールがあった後に、スリーベットすること。',
      en: 'A 3-bet made after an open raise and at least one call.',
    },
    example: { en: 'The big blind squeezed after the open and a call.', ja: 'オープンとコールの後、ビッグブラインドがスクイーズした。' },
  },
  {
    id: 'isolation-raise',
    en: 'Isolation raise',
    ja: 'アイソレーションレイズ',
    kana: 'あいそれーしょんれいず',
    aliases: ['iso', 'iso-raise'],
    def: {
      ja: 'リンプした弱いプレイヤーと1対1になるために、レイズして他を降ろすこと。',
      en: 'Raising over a limper to play the pot heads-up against that weak player.',
    },
    example: { en: 'Make a big isolation raise over the fish.', ja: 'フィッシュのリンプには大きくアイソレーションレイズする。' },
  },
  {
    id: 'c-bet',
    en: 'C-bet',
    ja: 'Cベット',
    kana: 'しーべっと',
    aliases: ['cbet', 'continuation bet', 'コンティニュエーションベット'],
    def: {
      ja: 'プリフロップで最後にレイズした人が、フロップでも続けてベットすること。',
      en: 'A flop bet by the player who made the last raise preflop.',
    },
    example: { en: 'I c-bet a third pot on a dry board.', ja: 'ドライボードでポットの3分の1をCベットした。' },
  },
  {
    id: 'donk-bet',
    en: 'Donk bet',
    ja: 'ドンクベット',
    kana: 'どんくべっと',
    aliases: ['lead'],
    def: {
      ja: '前のストリートで主導権を持っていた相手に対して、先にベットすること。',
      en: 'Betting out into the player who had the betting lead on the previous street.',
    },
    example: { en: 'The big blind donk bet the turn.', ja: 'ビッグブラインドがターンでドンクベットした。' },
  },
  {
    id: 'check-raise',
    en: 'Check-raise',
    ja: 'チェックレイズ',
    kana: 'ちぇっくれいず',
    aliases: ['x/r'],
    def: {
      ja: '一度チェックし、相手がベットしてからレイズすること。',
      en: 'Checking, then raising after an opponent bets.',
    },
    example: { en: 'She check-raised the flop with a set.', ja: 'セットでフロップをチェックレイズした。' },
  },
  {
    id: 'probe-bet',
    en: 'Probe bet',
    ja: 'プローブベット',
    kana: 'ぷろーぶべっと',
    def: {
      ja: '相手がフロップでCベットせずにチェックした後、アウトオブポジションからターンでベットすること。',
      en: 'An out-of-position turn bet after the preflop raiser checked back the flop.',
    },
    example: { en: 'When the flop checks through, probe bet the turn.', ja: 'フロップがチェックで回ったら、ターンでプローブベットする。' },
  },
  {
    id: 'float',
    en: 'Float',
    ja: 'フロート',
    kana: 'ふろーと',
    def: {
      ja: '弱いハンドでベットにコールし、後のストリートでポットを奪うつもりでいること。',
      en: 'Calling a bet with a weak hand, planning to take the pot away on a later street.',
    },
    example: { en: 'He floated the flop and bet when checked to.', ja: 'フロップをフロートし、チェックで回ってきたらベットした。' },
  },
  {
    id: 'overbet',
    en: 'Overbet',
    ja: 'オーバーベット',
    kana: 'おーばーべっと',
    def: {
      ja: 'ポットより大きい額をベットすること。',
      en: 'A bet larger than the pot.',
    },
    example: { en: 'An overbet on the river polarizes your range.', ja: 'リバーのオーバーベットはレンジを両極にする。' },
  },
  {
    id: 'block-bet',
    en: 'Block bet',
    ja: 'ブロックベット',
    kana: 'ぶろっくべっと',
    aliases: ['blocker bet'],
    def: {
      ja: '相手に大きくベットさせないために、先に小さくベットすること。',
      en: 'A small bet made first to stop an opponent from making a larger one.',
    },
    example: { en: 'I made a block bet on the river with a medium hand.', ja: '中くらいのハンドでリバーにブロックベットした。' },
  },
  {
    id: 'all-in',
    en: 'All-in',
    ja: 'オールイン',
    kana: 'おーるいん',
    aliases: ['shove', 'jam'],
    def: {
      ja: '持っているチップをすべて賭けること。',
      en: 'Betting every chip you have.',
    },
    example: { en: 'With ten big blinds left, he went all-in.', ja: '残り10ビッグブラインドでオールインした。' },
  },
  {
    id: 'slow-play',
    en: 'Slow play',
    ja: 'スロープレイ',
    kana: 'すろーぷれい',
    aliases: ['sandbag'],
    def: {
      ja: '強いハンドを弱く見せるために、ベットやレイズをせずにチェックやコールで進めること。',
      en: 'Checking or calling with a strong hand to disguise its strength.',
    },
    example: { en: 'Slow playing a set on a wet board is risky.', ja: 'ウェットボードでセットをスロープレイするのは危ない。' },
  },
  {
    id: 'check-back',
    en: 'Check back',
    ja: 'チェックバック',
    kana: 'ちぇっくばっく',
    def: {
      ja: '相手がチェックした後に、最後に行動する人もチェックしてストリートを終えること。',
      en: 'Checking behind as the last player to act after your opponent checks.',
    },
    example: { en: 'He checked back the flop with ace high.', ja: 'エースハイでフロップをチェックバックした。' },
  },
  {
    id: 'steal',
    en: 'Steal',
    ja: 'スチール',
    kana: 'すちーる',
    aliases: ['blind steal'],
    def: {
      ja: 'レイトポジションからレイズして、ブラインドを奪おうとすること。',
      en: 'Raising from late position to win the blinds uncontested.',
    },
    example: { en: 'The button tries to steal almost every orbit.', ja: 'ボタンはほぼ毎周スチールを狙ってくる。' },
  },
];
