import type { Term } from './types';

export const HAND_BOARD: Term[] = [
  {
    id: 'pocket-pair',
    en: 'Pocket pair',
    ja: 'ポケットペア',
    kana: 'ぽけっとぺあ',
    aliases: ['pocket'],
    def: {
      ja: '手札の2枚が同じ数字であること。例: 7♠7♦。',
      en: 'Two hole cards of the same rank, such as 7♠7♦.',
    },
    example: { en: 'Small pocket pairs play for set value.', ja: '小さいポケットペアはセットを狙って打つ。' },
  },
  {
    id: 'suited',
    en: 'Suited',
    ja: 'スーテッド',
    kana: 'すーてっど',
    aliases: ['s'],
    def: {
      ja: '手札の2枚が同じスートであること。表記では末尾に s を付ける（例: AKs）。',
      en: 'Two hole cards of the same suit, written with a trailing s (AKs).',
    },
    example: { en: 'Suited hands make flushes and play better postflop.', ja: 'スーテッドはフラッシュになるのでポストフロップで打ちやすい。' },
  },
  {
    id: 'offsuit',
    en: 'Offsuit',
    ja: 'オフスート',
    kana: 'おふすーと',
    aliases: ['o'],
    def: {
      ja: '手札の2枚が違うスートであること。表記では末尾に o を付ける（例: AKo）。',
      en: 'Two hole cards of different suits, written with a trailing o (AKo).',
    },
    example: { en: 'Fold weak offsuit aces from early position.', ja: 'アーリーポジションでは弱いオフスートのエースを降りる。' },
  },
  {
    id: 'suited-connectors',
    en: 'Suited connectors',
    ja: 'スーテッドコネクター',
    kana: 'すーてっどこねくたー',
    aliases: ['SC'],
    def: {
      ja: '同じスートで数字が連続した2枚。例: 8♥7♥。',
      en: 'Two consecutive ranks of the same suit, such as 8♥7♥.',
    },
    example: { en: 'Suited connectors play well in multiway pots.', ja: 'スーテッドコネクターは多人数のポットで強い。' },
  },
  {
    id: 'broadway',
    en: 'Broadway',
    ja: 'ブロードウェイ',
    kana: 'ぶろーどうぇい',
    def: {
      ja: 'T、J、Q、K、A の5枚のカードの総称。この5枚でできたストレートも指す。',
      en: 'The five cards ten through ace, or the ace-high straight they make.',
    },
    example: { en: 'Two broadway cards like KQ are a solid open.', ja: 'KQ のようなブロードウェイ2枚は堅いオープンだ。' },
  },
  {
    id: 'overpair',
    en: 'Overpair',
    ja: 'オーバーペア',
    kana: 'おーばーぺあ',
    def: {
      ja: 'ボードのどのカードよりも高いポケットペア。',
      en: 'A pocket pair higher than every card on the board.',
    },
    example: { en: 'Queens are an overpair on a 9-7-2 flop.', ja: '9-7-2 のフロップでは Q のペアがオーバーペアだ。' },
  },
  {
    id: 'top-pair',
    en: 'Top pair',
    ja: 'トップペア',
    kana: 'とっぷぺあ',
    aliases: ['TP'],
    def: {
      ja: 'ボードで一番高いカードとペアになった状態。',
      en: 'A pair made with the highest card on the board.',
    },
    example: { en: 'Top pair, good kicker is usually worth two streets of value.', ja: 'トップペアでキッカーが強ければ、たいてい2ストリート分バリューを取れる。' },
  },
  {
    id: 'kicker',
    en: 'Kicker',
    ja: 'キッカー',
    kana: 'きっかー',
    def: {
      ja: '役に使われていない手札のカード。同じ役どうしの勝敗を決める。',
      en: 'The unpaired side card that breaks ties between equal hands.',
    },
    example: { en: 'We both had an ace, but his kicker was better.', ja: 'どちらもエースのペアだったが、相手のキッカーが上だった。' },
  },
  {
    id: 'set',
    en: 'Set',
    ja: 'セット',
    kana: 'せっと',
    def: {
      ja: 'ポケットペアとボードの1枚で作ったスリーカード。',
      en: 'Three of a kind made with a pocket pair and one matching board card.',
    },
    example: { en: 'He flopped a set of fives.', ja: 'フロップで5のセットができた。' },
  },
  {
    id: 'trips',
    en: 'Trips',
    ja: 'トリップス',
    kana: 'とりっぷす',
    def: {
      ja: 'ボードのペアと手札の1枚で作ったスリーカード。セットより相手に読まれやすい。',
      en: 'Three of a kind made with a board pair and one hole card; easier to read than a set.',
    },
    example: { en: 'On a paired board, trips can still lose to a better kicker.', ja: 'ペアボードでは、トリップスでもキッカー負けすることがある。' },
  },
  {
    id: 'two-pair',
    en: 'Two pair',
    ja: 'ツーペア',
    kana: 'つーぺあ',
    def: {
      ja: 'ペアが2組ある役。',
      en: 'A hand with two different pairs.',
    },
    example: { en: 'Top two pair is strong on a dry flop.', ja: 'ドライなフロップでのトップツーペアは強い。' },
  },
  {
    id: 'flush-draw',
    en: 'Flush draw',
    ja: 'フラッシュドロー',
    kana: 'ふらっしゅどろー',
    aliases: ['FD'],
    def: {
      ja: 'あと1枚同じスートが来ればフラッシュになる状態。アウツは9枚。',
      en: 'Four cards to a flush, needing one more of the suit; nine outs.',
    },
    example: { en: 'A flush draw on the flop hits by the river about 35% of the time.', ja: 'フロップのフラッシュドローはリバーまでに約35%で完成する。' },
  },
  {
    id: 'oesd',
    en: 'Open-ended straight draw',
    ja: 'オープンエンド',
    kana: 'おーぷんえんど',
    aliases: ['OESD', 'open-ender', 'オープンエンドストレートドロー'],
    def: {
      ja: '連続した4枚があり、両端のどちらが来てもストレートになる状態。アウツは8枚。',
      en: 'Four consecutive cards that make a straight with a card at either end; eight outs.',
    },
    example: { en: 'With 9-8 on a 7-6-2 flop you have an open-ended straight draw.', ja: '7-6-2 のフロップで 9-8 ならオープンエンドだ。' },
  },
  {
    id: 'gutshot',
    en: 'Gutshot',
    ja: 'ガットショット',
    kana: 'がっとしょっと',
    aliases: ['inside straight draw'],
    def: {
      ja: '間の1枚が来ればストレートになる状態。アウツは4枚。',
      en: 'A straight draw that needs one specific inside rank; four outs.',
    },
    example: { en: 'Don’t chase a gutshot without the right price.', ja: 'オッズが合わないならガットショットは追わない。' },
  },
  {
    id: 'backdoor-draw',
    en: 'Backdoor draw',
    ja: 'バックドアドロー',
    kana: 'ばっくどあどろー',
    aliases: ['backdoor'],
    def: {
      ja: 'ターンとリバーの2枚が両方来て初めて完成するドロー。',
      en: 'A draw that needs both the turn and the river to complete.',
    },
    example: { en: 'A backdoor flush draw adds a little equity to your bluff.', ja: 'バックドアのフラッシュドローがあるとブラフの勝率が少し上がる。' },
  },
  {
    id: 'combo-draw',
    en: 'Combo draw',
    ja: 'コンボドロー',
    kana: 'こんぼどろー',
    def: {
      ja: 'フラッシュドローとストレートドローを同時に持っている状態。アウツが多く強い。',
      en: 'A flush draw and a straight draw at the same time, with many outs.',
    },
    example: { en: 'Get it in on the flop with a big combo draw.', ja: '大きなコンボドローならフロップでオールインしていい。' },
  },
  {
    id: 'dry-board',
    en: 'Dry board',
    ja: 'ドライボード',
    kana: 'どらいぼーど',
    def: {
      ja: 'ストレートやフラッシュのドローがほとんどない、つながりの薄いボード。例: K♠7♦2♣。',
      en: 'A disconnected board with few straight or flush draws, such as K♠7♦2♣.',
    },
    example: { en: 'C-bet small on a dry board.', ja: 'ドライボードでは小さくCベットする。' },
  },
  {
    id: 'wet-board',
    en: 'Wet board',
    ja: 'ウェットボード',
    kana: 'うぇっとぼーど',
    def: {
      ja: 'ストレートやフラッシュのドローが多い、つながったボード。例: J♥T♥8♣。',
      en: 'A connected board with many straight and flush draws, such as J♥T♥8♣.',
    },
    example: { en: 'Protect your hand on a wet board.', ja: 'ウェットボードでは自分のハンドを守るためにベットする。' },
  },
  {
    id: 'monotone',
    en: 'Monotone',
    ja: 'モノトーン',
    kana: 'ものとーん',
    def: {
      ja: 'フロップの3枚がすべて同じスートであること。',
      en: 'A flop with all three cards of the same suit.',
    },
    example: { en: 'The flop came monotone hearts.', ja: 'フロップはハートのモノトーンだった。' },
  },
  {
    id: 'rainbow',
    en: 'Rainbow',
    ja: 'レインボー',
    kana: 'れいんぼー',
    def: {
      ja: 'フロップの3枚がすべて違うスートであること。フラッシュドローができない。',
      en: 'A flop with three different suits, so no flush draw is possible.',
    },
    example: { en: 'A rainbow flop favors the preflop raiser.', ja: 'レインボーのフロップはプリフロップのレイザーに有利だ。' },
  },
  {
    id: 'paired-board',
    en: 'Paired board',
    ja: 'ペアボード',
    kana: 'ぺあぼーど',
    def: {
      ja: 'ボードに同じ数字のカードが2枚あること。フルハウスやトリップスの可能性が出る。',
      en: 'A board with two cards of the same rank, which makes full houses and trips possible.',
    },
    example: { en: 'Bet small and often on a paired board.', ja: 'ペアボードでは小さく頻繁にベットする。' },
  },
  {
    id: 'blocker',
    en: 'Blocker',
    ja: 'ブロッカー',
    kana: 'ぶろっかー',
    def: {
      ja: '自分が持っているために、相手がそのカードを含む強いハンドを持つ可能性を減らすカード。',
      en: 'A card you hold that makes it less likely your opponent has a hand containing it.',
    },
    example: { en: 'The ace of hearts is a great blocker to the nut flush.', ja: 'ハートのエースはナッツフラッシュへの強いブロッカーだ。' },
  },
];
