import type { Term } from './types';

export const MATH: Term[] = [
  {
    id: 'pot-odds',
    en: 'Pot odds',
    ja: 'ポットオッズ',
    kana: 'ぽっとおっず',
    def: {
      ja: '今のポットの額と、コールに必要な額の比率。ここからコールに必要な勝率が分かる。',
      en: 'The ratio of the current pot to the cost of calling, which tells you the equity a call needs.',
    },
    example: { en: 'A half-pot bet gives you 3-to-1 pot odds.', ja: 'ポットの半分のベットなら、ポットオッズは3対1だ。' },
  },
  {
    id: 'equity',
    en: 'Equity',
    ja: 'エクイティ',
    kana: 'えくいてぃ',
    aliases: ['勝率'],
    def: {
      ja: '残りのカードがすべて配られたときに、そのハンドがポットを取る割合。',
      en: 'The share of the pot a hand wins on average if all remaining cards are dealt.',
    },
    example: { en: 'Aces have about 80% equity against kings.', ja: 'AA は KK に対して約80%のエクイティがある。' },
  },
  {
    id: 'ev',
    en: 'EV',
    ja: 'EV',
    kana: 'いーぶい',
    aliases: ['expected value', '期待値'],
    def: {
      ja: '期待値。その選択を何度も繰り返したときに、1回あたり平均でいくら得するか。',
      en: 'Expected value: the average amount a decision wins or loses if repeated many times.',
    },
    example: { en: 'Calling here is +EV even if you lose this time.', ja: '今回負けても、ここでのコールはプラスEVだ。' },
  },
  {
    id: 'outs',
    en: 'Outs',
    ja: 'アウツ',
    kana: 'あうつ',
    def: {
      ja: '次に来れば自分のハンドが勝ちになるカードの枚数。',
      en: 'The unseen cards that would turn your hand into the winner.',
    },
    example: { en: 'With a flush draw you have nine outs.', ja: 'フラッシュドローならアウツは9枚だ。' },
  },
  {
    id: 'spr',
    en: 'SPR',
    ja: 'SPR',
    kana: 'えすぴーあーる',
    aliases: ['stack-to-pot ratio'],
    def: {
      ja: 'フロップ時点のエフェクティブスタックをポットの額で割った値。低いほどオールインしやすい。',
      en: 'Effective stack divided by the pot on the flop; the lower it is, the easier it is to get all-in.',
    },
    example: { en: 'With an SPR of 2, top pair is happy to get it in.', ja: 'SPR が2なら、トップペアでオールインしてかまわない。' },
  },
  {
    id: 'implied-odds',
    en: 'Implied odds',
    ja: 'インプライドオッズ',
    kana: 'いんぷらいどおっず',
    def: {
      ja: 'ドローが完成した後に相手から追加で取れそうなチップまで含めて考えたオッズ。',
      en: 'Pot odds that also count the chips you expect to win later when your draw hits.',
    },
    example: { en: 'Small pairs need implied odds to call a raise.', ja: '小さいペアでレイズにコールするにはインプライドオッズが要る。' },
  },
  {
    id: 'reverse-implied-odds',
    en: 'Reverse implied odds',
    ja: 'リバースインプライドオッズ',
    kana: 'りばーすいんぷらいどおっず',
    aliases: ['RIO'],
    def: {
      ja: 'ハンドが完成しても、より強いハンドに負けて大きく失う可能性のこと。',
      en: 'The risk of losing a big pot when your hand improves but is still second best.',
    },
    example: { en: 'Weak aces suffer from reverse implied odds.', ja: '弱いエースはリバースインプライドオッズに苦しむ。' },
  },
  {
    id: 'mdf',
    en: 'MDF',
    ja: 'MDF',
    kana: 'えむでぃーえふ',
    aliases: ['minimum defense frequency'],
    def: {
      ja: '相手のブラフを利益にさせないために、ベットに対して降りずに続けるべき最低限の割合。',
      en: 'Minimum defense frequency: how often you must continue so a bluff cannot profit automatically.',
    },
    example: { en: 'Against a pot-sized bet, MDF is 50%.', ja: 'ポットサイズのベットに対する MDF は50%だ。' },
  },
  {
    id: 'fold-equity',
    en: 'Fold equity',
    ja: 'フォールドエクイティ',
    kana: 'ふぉーるどえくいてぃ',
    aliases: ['FE'],
    def: {
      ja: 'ベットやレイズで相手を降ろせることから生まれる価値。',
      en: 'The value a bet or raise gains from the chance that your opponent folds.',
    },
    example: { en: 'Shoving early keeps your fold equity high.', ja: '早めにオールインすればフォールドエクイティを保てる。' },
  },
  {
    id: 'effective-stack',
    en: 'Effective stack',
    ja: 'エフェクティブスタック',
    kana: 'えふぇくてぃぶすたっく',
    def: {
      ja: '対戦している中で一番少ないスタック。実際に失ったり得たりできる最大額になる。',
      en: 'The smallest stack among the players in the hand, the most that can actually be won or lost.',
    },
    example: { en: 'The effective stack is 40bb, so a 3-bet commits us.', ja: 'エフェクティブスタックが 40bb なので、3ベットしたら引けない。' },
  },
  {
    id: 'combos',
    en: 'Combos',
    ja: 'コンボ',
    kana: 'こんぼ',
    aliases: ['combinations'],
    def: {
      ja: 'あるハンドが取りうるカードの組み合わせの数。ポケットペアは6通り、スーテッドは4通り。',
      en: 'The number of card combinations a hand can take: six for a pocket pair, four for a suited hand.',
    },
    example: { en: 'There are 16 combos of AK before any cards are removed.', ja: 'カードが見えていなければ AK は16コンボある。' },
  },
  {
    id: 'range',
    en: 'Range',
    ja: 'レンジ',
    kana: 'れんじ',
    def: {
      ja: 'ある状況でプレイヤーが持っていうるハンドの集まり。',
      en: 'The set of hands a player could hold in a given spot.',
    },
    example: { en: 'Put him on a range, not a single hand.', ja: '相手を1つのハンドではなくレンジで考える。' },
  },
  {
    id: 'range-advantage',
    en: 'Range advantage',
    ja: 'レンジアドバンテージ',
    kana: 'れんじあどばんてーじ',
    def: {
      ja: 'そのボードで、自分のレンジ全体の勝率が相手のレンジより高いこと。',
      en: 'Having more overall equity with your range than your opponent has with theirs on a board.',
    },
    example: { en: 'The raiser has the range advantage on an ace-high flop.', ja: 'エースハイのフロップではレイザーにレンジアドバンテージがある。' },
  },
  {
    id: 'nut-advantage',
    en: 'Nut advantage',
    ja: 'ナッツアドバンテージ',
    kana: 'なっつあどばんてーじ',
    def: {
      ja: 'そのボードで、最も強いハンドを相手より多く持っていること。大きいベットの根拠になる。',
      en: 'Holding more of the strongest possible hands than your opponent, which supports large bets.',
    },
    example: { en: 'With the nut advantage, you can overbet.', ja: 'ナッツアドバンテージがあればオーバーベットできる。' },
  },
  {
    id: 'polarized',
    en: 'Polarized',
    ja: 'ポラライズ',
    kana: 'ぽららいず',
    aliases: ['polar'],
    def: {
      ja: 'レンジが強いハンドとブラフだけで、中くらいのハンドを含まない状態。',
      en: 'A range made of strong hands and bluffs, with no medium-strength hands.',
    },
    example: { en: 'A big river bet usually comes from a polarized range.', ja: 'リバーの大きいベットはたいていポラライズしたレンジから来る。' },
  },
  {
    id: 'linear',
    en: 'Linear',
    ja: 'リニア',
    kana: 'りにあ',
    aliases: ['merged'],
    def: {
      ja: 'レンジが上から順に強いハンドで構成され、ブラフをあまり含まない状態。',
      en: 'A range built from the strongest hands downward, with few bluffs.',
    },
    example: { en: 'Against a calling station, 3-bet a linear range.', ja: 'コーリングステーションにはリニアなレンジで3ベットする。' },
  },
  {
    id: 'bluff-to-value',
    en: 'Bluff-to-value ratio',
    ja: 'ブラフとバリューの比率',
    kana: 'ぶらふとばりゅーのひりつ',
    def: {
      ja: 'ベットするレンジに含めるブラフとバリューハンドの割合。ベットサイズで最適な比率が変わる。',
      en: 'The proportion of bluffs to value hands in a betting range; the right mix depends on bet size.',
    },
    example: { en: 'A pot-sized river bet allows one bluff for every two value hands.', ja: 'リバーでポットサイズなら、バリュー2つにつきブラフ1つまで入れられる。' },
  },
  {
    id: 'bb-per-100',
    en: 'bb/100',
    ja: 'bb/100',
    kana: 'びーびーぱーひゃく',
    aliases: ['winrate'],
    def: {
      ja: '100ハンドあたりに勝ったビッグブラインドの数。キャッシュゲームの勝率の指標。',
      en: 'Big blinds won per 100 hands, the standard cash-game win rate.',
    },
    example: { en: 'A 5 bb/100 win rate is solid at small stakes.', ja: '低レートで 5bb/100 なら十分勝てている。' },
  },
  {
    id: 'variance',
    en: 'Variance',
    ja: 'バリアンス',
    kana: 'ばりあんす',
    def: {
      ja: '運による結果のぶれ。正しく打っていても短期間では負けることがある。',
      en: 'The swings in results caused by luck, which can hide good play in the short run.',
    },
    example: { en: 'A 30-buy-in downswing is just variance.', ja: '30バイイン負けたのもただのバリアンスだ。' },
  },
  {
    id: 'gto',
    en: 'GTO',
    ja: 'GTO',
    kana: 'じーてぃーおー',
    aliases: ['game theory optimal'],
    def: {
      ja: 'ゲーム理論的に最適な戦略。相手がどう打っても長期的に負けない打ち方。',
      en: 'Game theory optimal: a strategy that cannot be exploited, whatever the opponent does.',
    },
    example: { en: 'Solvers show the GTO play for each spot.', ja: 'ソルバーは各局面の GTO の打ち方を示す。' },
  },
  {
    id: 'icm',
    en: 'ICM',
    ja: 'ICM',
    kana: 'あいしーえむ',
    aliases: ['independent chip model'],
    def: {
      ja: 'トーナメントのチップを賞金の期待値に換算するモデル。チップを失う痛手が得る価値より大きくなる。',
      en: 'A model that converts tournament chips into prize equity; chips lost hurt more than chips won help.',
    },
    example: { en: 'ICM says fold this near the final table.', ja: 'ファイナルテーブル目前では ICM 的にフォールドだ。' },
  },
];
