import type { Term } from './types';

export const POSITION: Term[] = [
  {
    id: 'utg',
    en: 'UTG',
    ja: 'アンダーザガン',
    kana: 'あんだーざがん',
    aliases: ['under the gun'],
    def: {
      ja: 'プリフロップで最初に行動するポジション。ビッグブラインドの左隣。',
      en: 'The first seat to act preflop, directly left of the big blind.',
    },
    example: { en: 'Play tight from UTG.', ja: 'UTG ではタイトに打つ。' },
  },
  {
    id: 'utg-1',
    en: 'UTG+1',
    ja: 'UTG+1',
    kana: 'ゆーてぃーじーぷらすわん',
    aliases: ['under the gun plus one'],
    def: {
      ja: 'UTG の左隣のポジション。プリフロップで2番目に行動する。',
      en: 'The seat directly left of UTG, second to act preflop.',
    },
    example: { en: 'He opened from UTG+1 at a full-ring table.', ja: 'フルリングで UTG+1 からオープンした。' },
  },
  {
    id: 'middle-position',
    en: 'Middle position',
    ja: 'ミドルポジション',
    kana: 'みどるぽじしょん',
    aliases: ['MP'],
    def: {
      ja: 'アーリーポジションとレイトポジションの間の席。中くらいの広さでオープンする。',
      en: 'The seats between early and late position, where opening ranges are medium width.',
    },
    example: { en: 'A raise from middle position usually means a solid hand.', ja: 'ミドルポジションからのレイズは、たいてい堅いハンドだ。' },
  },
  {
    id: 'hijack',
    en: 'Hijack',
    ja: 'ハイジャック',
    kana: 'はいじゃっく',
    aliases: ['HJ'],
    def: {
      ja: 'カットオフの右隣のポジション。6-max ではプリフロップで2番目に行動する。',
      en: 'The seat to the right of the cutoff; second to act preflop at a 6-max table.',
    },
    example: { en: 'The hijack opened and the button 3-bet.', ja: 'ハイジャックがオープンし、ボタンが3ベットした。' },
  },
  {
    id: 'cutoff',
    en: 'Cutoff',
    ja: 'カットオフ',
    kana: 'かっとおふ',
    aliases: ['CO'],
    def: {
      ja: 'ボタンの右隣のポジション。ボタンの次に有利で、広くオープンできる。',
      en: 'The seat to the right of the button, the second-best position and a wide opening spot.',
    },
    example: { en: 'Open wide from the cutoff when the button is tight.', ja: 'ボタンがタイトならカットオフから広くオープンする。' },
  },
  {
    id: 'button',
    en: 'Button',
    ja: 'ボタン',
    kana: 'ぼたん',
    aliases: ['BTN', 'dealer'],
    def: {
      ja: 'ディーラーの位置。フロップ以降は常に最後に行動できる、最も有利なポジション。',
      en: 'The dealer seat, which acts last on every postflop street and is the most profitable position.',
    },
    example: { en: 'Open wider on the button.', ja: 'ボタンでは広くオープンする。' },
  },
  {
    id: 'small-blind',
    en: 'Small blind',
    ja: 'スモールブラインド',
    kana: 'すもーるぶらいんど',
    aliases: ['SB'],
    def: {
      ja: 'ボタンの左隣で、強制的に小さいベットを払うポジション。フロップ以降は最初に行動する。',
      en: 'The seat left of the button that posts the smaller forced bet and acts first after the flop.',
    },
    example: { en: 'Folding the small blind every orbit adds up.', ja: 'スモールブラインドを毎周フォールドすると、損が積み重なる。' },
  },
  {
    id: 'big-blind',
    en: 'Big blind',
    ja: 'ビッグブラインド',
    kana: 'びっぐぶらいんど',
    aliases: ['BB'],
    def: {
      ja: 'スモールブラインドの左隣で、大きいほうの強制ベットを払うポジション。プリフロップで最後に行動する。',
      en: 'The seat that posts the larger forced bet and acts last preflop.',
    },
    example: { en: 'Defend your big blind against button steals.', ja: 'ボタンのスチールにはビッグブラインドで守る。' },
  },
  {
    id: 'early-position',
    en: 'Early position',
    ja: 'アーリーポジション',
    kana: 'あーりーぽじしょん',
    aliases: ['EP'],
    def: {
      ja: 'プリフロップで早く行動する席の総称。後ろに多くのプレイヤーが残るので狭いレンジで打つ。',
      en: 'The seats that act first preflop; with many players left behind, ranges are tight.',
    },
    example: { en: 'An early position open deserves respect.', ja: 'アーリーポジションのオープンは警戒したほうがいい。' },
  },
  {
    id: 'late-position',
    en: 'Late position',
    ja: 'レイトポジション',
    kana: 'れいとぽじしょん',
    aliases: ['LP'],
    def: {
      ja: 'カットオフとボタンのこと。後から行動できるので、広いレンジで参加できる。',
      en: 'The cutoff and the button, which act late and can play the widest ranges.',
    },
    example: { en: 'Most of your profit comes from late position.', ja: '利益の大半はレイトポジションから生まれる。' },
  },
  {
    id: 'in-position',
    en: 'In position',
    ja: 'インポジション',
    kana: 'いんぽじしょん',
    aliases: ['IP'],
    def: {
      ja: 'ポストフロップで相手より後に行動できる状態。相手の動きを見てから決められる。',
      en: 'Acting after your opponent after the flop, so you see their action before deciding.',
    },
    example: { en: 'Calling is easier when you are in position.', ja: 'インポジションならコールしやすい。' },
  },
  {
    id: 'out-of-position',
    en: 'Out of position',
    ja: 'アウトオブポジション',
    kana: 'あうとおぶぽじしょん',
    aliases: ['OOP'],
    def: {
      ja: 'ポストフロップで相手より先に行動しなければならない状態。情報が少なく不利になる。',
      en: 'Having to act before your opponent after the flop, with less information.',
    },
    example: { en: 'Playing big pots out of position is costly.', ja: 'アウトオブポジションで大きなポットを戦うと損をしやすい。' },
  },
  {
    id: 'straddle',
    en: 'Straddle',
    ja: 'ストラドル',
    kana: 'すとらどる',
    def: {
      ja: 'UTG がカードを見る前に、ビッグブラインドの2倍を任意で払うこと。プリフロップで最後に行動できる。',
      en: 'An optional blind of twice the big blind, posted by UTG before the deal, that buys the last preflop action.',
    },
    example: { en: 'The live game allows a straddle from any seat.', ja: 'そのライブゲームではどの席からでもストラドルできる。' },
  },
  {
    id: 'heads-up',
    en: 'Heads-up',
    ja: 'ヘッズアップ',
    kana: 'へっずあっぷ',
    aliases: ['HU'],
    def: {
      ja: '2人だけで対戦すること。テーブル全体が2人の場合も、ポットが2人に絞られた場合も言う。',
      en: 'Playing one against one, either at a two-player table or in a pot down to two players.',
    },
    example: { en: 'We went to the flop heads-up.', ja: 'ヘッズアップでフロップに進んだ。' },
  },
  {
    id: 'six-max',
    en: '6-max',
    ja: '6マックス',
    kana: 'しっくすまっくす',
    aliases: ['6max', 'six-handed'],
    def: {
      ja: '最大6人で遊ぶテーブル。フルリングより参加するハンドが広く、攻撃的になりやすい。',
      en: 'A table seating at most six players, with wider and more aggressive ranges than full ring.',
    },
    example: { en: 'Online cash games are mostly 6-max.', ja: 'オンラインのキャッシュゲームはほとんど6マックスだ。' },
  },
  {
    id: 'full-ring',
    en: 'Full ring',
    ja: 'フルリング',
    kana: 'ふるりんぐ',
    aliases: ['9-max'],
    def: {
      ja: '9〜10人で遊ぶテーブル。ライブのポーカーでは一般的な形式。',
      en: 'A table of nine or ten players, the usual format in live poker.',
    },
    example: { en: 'Full ring games play tighter than 6-max.', ja: 'フルリングは6マックスよりタイトになる。' },
  },
];
