import type { Term } from './types';

export const SLANG: Term[] = [
  {
    id: 'nuts',
    en: 'Nuts',
    ja: 'ナッツ',
    kana: 'なっつ',
    aliases: ['the nuts'],
    def: {
      ja: 'その時点のボードで作れる最も強いハンド。',
      en: 'The best possible hand on the current board.',
    },
    example: { en: 'He had the nuts on the river.', ja: 'リバーで彼はナッツだった。' },
  },
  {
    id: 'bad-beat',
    en: 'Bad beat',
    ja: 'バッドビート',
    kana: 'ばっどびーと',
    def: {
      ja: '大きく有利だったハンドが、低い確率のカードで逆転されて負けること。',
      en: 'Losing with a big favorite when the opponent hits a long shot.',
    },
    example: { en: 'Aces lost to a runner-runner flush, a classic bad beat.', ja: 'AA がランナーランナーのフラッシュに負けた。典型的なバッドビートだ。' },
  },
  {
    id: 'cooler',
    en: 'Cooler',
    ja: 'クーラー',
    kana: 'くーらー',
    def: {
      ja: '強いハンドどうしがぶつかり、どちらも降りられずに大きく負けること。ミスではない。',
      en: 'A strong hand losing to an even stronger one where neither player could fold; not a mistake.',
    },
    example: { en: 'Set over set is a cooler.', ja: 'セット対セットはクーラーだ。' },
  },
  {
    id: 'tilt',
    en: 'Tilt',
    ja: 'ティルト',
    kana: 'てぃると',
    aliases: ['tilted'],
    def: {
      ja: '負けや不運で冷静さを失い、判断が崩れている状態。',
      en: 'Playing badly because frustration or bad luck has taken over your judgment.',
    },
    example: { en: 'After the bad beat he went on tilt.', ja: 'バッドビートの後、彼はティルトした。' },
  },
  {
    id: 'fish',
    en: 'Fish',
    ja: 'フィッシュ',
    kana: 'ふぃっしゅ',
    def: {
      ja: '下手で負けているプレイヤー。テーブルの利益の源になる。',
      en: 'A weak, losing player who is the main source of profit at a table.',
    },
    example: { en: 'Sit to the left of the fish.', ja: 'フィッシュの左隣に座る。' },
  },
  {
    id: 'reg',
    en: 'Reg',
    ja: 'レギュラー',
    kana: 'れぎゅらー',
    aliases: ['regular'],
    def: {
      ja: 'そのレートに常にいる、堅実に打つ常連のプレイヤー。',
      en: 'A regular at the stakes who plays a solid, studied game.',
    },
    example: { en: 'The table is full of regs tonight.', ja: '今夜のテーブルはレギュラーばかりだ。' },
  },
  {
    id: 'nit',
    en: 'Nit',
    ja: 'ニット',
    kana: 'にっと',
    def: {
      ja: '強いハンドでしか参加しない、極端にタイトなプレイヤー。',
      en: 'An extremely tight player who only plays premium hands.',
    },
    example: { en: 'When the nit raises, fold your marginal hands.', ja: 'ニットがレイズしたら微妙なハンドは降りる。' },
  },
  {
    id: 'lag',
    en: 'LAG',
    ja: 'LAG',
    kana: 'らぐ',
    aliases: ['loose aggressive', 'ルースアグレッシブ'],
    def: {
      ja: 'ルースアグレッシブ。多くのハンドに参加し、積極的にベットやレイズをするスタイル。',
      en: 'Loose-aggressive: playing many hands and betting and raising often.',
    },
    example: { en: 'A good LAG is hard to play against.', ja: 'うまい LAG は相手にしにくい。' },
  },
  {
    id: 'tag',
    en: 'TAG',
    ja: 'TAG',
    kana: 'たぐ',
    aliases: ['tight aggressive', 'タイトアグレッシブ'],
    def: {
      ja: 'タイトアグレッシブ。参加するハンドを絞り、参加したら積極的に攻めるスタイル。',
      en: 'Tight-aggressive: playing few hands but betting and raising with them.',
    },
    example: { en: 'Most winning beginners start as TAGs.', ja: '勝てる初心者の多くは TAG から始める。' },
  },
  {
    id: 'maniac',
    en: 'Maniac',
    ja: 'マニアック',
    kana: 'まにあっく',
    def: {
      ja: 'ほとんどのハンドでレイズを繰り返す、極端に攻撃的なプレイヤー。',
      en: 'A hyper-aggressive player who raises with almost anything.',
    },
    example: { en: 'Let the maniac bluff into your strong hands.', ja: 'マニアックには強いハンドでブラフさせておく。' },
  },
  {
    id: 'calling-station',
    en: 'Calling station',
    ja: 'コーリングステーション',
    kana: 'こーりんぐすてーしょん',
    aliases: ['station'],
    def: {
      ja: 'ほとんど降りずにコールを続けるプレイヤー。ブラフが効かない。',
      en: 'A player who calls far too often and rarely folds, so bluffs do not work.',
    },
    example: { en: 'Never bluff a calling station; value bet thinly instead.', ja: 'コーリングステーションにはブラフせず、薄くバリューベットする。' },
  },
  {
    id: 'donk',
    en: 'Donk',
    ja: 'ドンク',
    kana: 'どんく',
    aliases: ['donkey'],
    def: {
      ja: '下手なプレイヤーを指す、やや失礼な言い方。',
      en: 'A rude word for a bad player.',
    },
    example: { en: 'Some donk called three streets with bottom pair.', ja: 'どこかのドンクがボトムペアで3ストリートコールしてきた。' },
  },
  {
    id: 'hero-call',
    en: 'Hero call',
    ja: 'ヒーローコール',
    kana: 'ひーろーこーる',
    def: {
      ja: '弱いハンドで、相手のブラフを読んで大きなベットにコールすること。',
      en: 'Calling a big bet with a weak hand because you read your opponent for a bluff.',
    },
    example: { en: 'She made a hero call with ace high and won.', ja: 'エースハイでヒーローコールして勝った。' },
  },
  {
    id: 'run-it-twice',
    en: 'Run it twice',
    ja: 'ランイットトゥワイス',
    kana: 'らんいっととぅわいす',
    aliases: ['RIT'],
    def: {
      ja: 'オールイン後に残りのボードを2回配り、ポットを半分ずつ分けること。運のぶれを減らす。',
      en: 'Dealing the remaining board twice after an all-in and splitting the pot between the runs to cut variance.',
    },
    example: { en: 'Do you want to run it twice?', ja: 'ランイットトゥワイスする？' },
  },
  {
    id: 'suckout',
    en: 'Suckout',
    ja: 'サックアウト',
    kana: 'さっくあうと',
    aliases: ['rivered', 'suck out'],
    def: {
      ja: '不利だったハンドが、後から来たカードで逆転して勝つこと。',
      en: 'Winning with the worse hand by hitting a card on a later street.',
    },
    example: { en: 'He sucked out with a two-outer on the river.', ja: 'リバーで2アウツを引いてサックアウトした。' },
  },
  {
    id: 'snap-call',
    en: 'Snap call',
    ja: 'スナップコール',
    kana: 'すなっぷこーる',
    aliases: ['snap'],
    def: {
      ja: '考える時間を取らずに即座にコールすること。強いハンドを示すことが多い。',
      en: 'Calling instantly without thinking, usually with a strong hand.',
    },
    example: { en: 'He snap called my shove with kings.', ja: '私のオールインに KK で即スナップコールした。' },
  },
  {
    id: 'bubble',
    en: 'Bubble',
    ja: 'バブル',
    kana: 'ばぶる',
    def: {
      ja: 'トーナメントで、あと1人飛べば全員が入賞する段階。',
      en: 'The point in a tournament where one more elimination puts everyone left in the money.',
    },
    example: { en: 'Big stacks should pressure short stacks on the bubble.', ja: 'バブルでは大きいスタックがショートスタックに圧力をかける。' },
  },
];
