import { writeFileSync } from 'node:fs';
import { HAND_CLASSES, combosOf, fullDeck, multiEquity, summarize, type WeightedCombo } from '@holdem-lab/engine';
import { test } from 'vitest';

const deck = fullDeck();
const RANDOM: WeightedCombo[] = [];
for (let i = 0; i < 52; i++) for (let j = i + 1; j < 52; j++) RANDOM.push({ combo: [deck[i], deck[j]], weight: 1 });

test('generate src/preflopEquity.ts', () => {
  const rows = HAND_CLASSES.map((hc, i) => {
    const stats = multiEquity(
      [
        { kind: 'hand', cards: combosOf(hc)[0] },
        { kind: 'range', combos: RANDOM },
      ],
      [],
      { mode: 'mc', iterations: 100_000, seed: i + 1 },
    );
    return `  '${hc}': ${summarize(stats).equity[0].toFixed(3)},`;
  });
  writeFileSync(
    new URL('../src/preflopEquity.ts', import.meta.url),
    `// Generated by scripts/gen-preflop-equity.gen.ts\n/* eslint-disable oxc/approx-constant */\nexport const PREFLOP_EQUITY: Record<string, number> = {\n${rows.join('\n')}\n};\n`,
  );
}, 900_000);
